SET EXPIRY_DATE_NTZ = '9999-08-17 07:31:29.901000000'::timestamp_ntz;
SET CURRENT_DATE_NTZ = TO_TIMESTAMP_NTZ(CURRENT_TIMESTAMP());

--INSERTING CHANGED/UPDATED ROWS
MERGE INTO POC.SNOWFLAKE_POC.CUSTOMER_TARGET CT
    USING POC.SNOWFLAKE_POC.CUSTOMER_STAGE CS ON CT.C_CUSTOMER_ID = CS.C_CUSTOMER_ID AND
                                                 (EQUAL_NULL(CT.C_FIRST_NAME, CS.C_FIRST_NAME) AND
                                                  EQUAL_NULL(CT.C_LAST_NAME, CS.C_LAST_NAME) AND
                                                  EQUAL_NULL(CT.C_BIRTH_YEAR, CS.C_BIRTH_YEAR) AND
                                                  EQUAL_NULL(CT.C_BIRTH_COUNTRY, CS.C_BIRTH_COUNTRY) AND
                                                  EQUAL_NULL(CT.C_LAST_REVIEW_DATE, CS.C_LAST_REVIEW_DATE)) AND
                                                 CT.TO_TIMESTAMP = $EXPIRY_DATE_NTZ
    WHEN NOT MATCHED THEN INSERT (C_CUSTOMER_ID, C_FIRST_NAME, C_LAST_NAME, C_BIRTH_YEAR, C_BIRTH_COUNTRY,
                                  C_LAST_REVIEW_DATE, FROM_TIMESTAMP, TO_TIMESTAMP)
        VALUES (CS.C_CUSTOMER_ID, CS.C_FIRST_NAME, CS.C_LAST_NAME, CS.C_BIRTH_YEAR, CS.C_BIRTH_COUNTRY,
                CS.C_LAST_REVIEW_DATE, $CURRENT_DATE_NTZ, $EXPIRY_DATE_NTZ);

UPDATE POC.SNOWFLAKE_POC.CUSTOMER_TARGET CT
SET CT.TO_TIMESTAMP = $CURRENT_DATE_NTZ
WHERE CT.C_CUSTOMER_ID NOT IN (SELECT C_CUSTOMER_ID FROM POC.SNOWFLAKE_POC.CUSTOMER_STAGE)
  AND CT.TO_TIMESTAMP = $EXPIRY_DATE_NTZ;

UPDATE POC.SNOWFLAKE_POC.CUSTOMER_TARGET CT
SET CT.TO_TIMESTAMP = $CURRENT_DATE_NTZ
FROM POC.SNOWFLAKE_POC.CUSTOMER_STAGE CS
WHERE CT.C_CUSTOMER_ID = CS.C_CUSTOMER_ID
  AND (CT.C_FIRST_NAME IS DISTINCT FROM CS.C_FIRST_NAME
    OR CT.C_LAST_NAME IS DISTINCT FROM CS.C_LAST_NAME
    OR CT.C_BIRTH_YEAR IS DISTINCT FROM CS.C_BIRTH_YEAR
    OR CT.C_BIRTH_COUNTRY IS DISTINCT FROM CS.C_BIRTH_COUNTRY
    OR CT.C_LAST_REVIEW_DATE IS DISTINCT FROM CS.C_LAST_REVIEW_DATE)
  AND CT.TO_TIMESTAMP = $EXPIRY_DATE_NTZ;
