DELETE FROM POC.SNOWFLAKE_POC.CUSTOMER_STAGE WHERE C_CUSTOMER_ID = 'AAAAAAAADHFEHNBA';
INSERT INTO POC.SNOWFLAKE_POC.CUSTOMER_STAGE (C_CUSTOMER_ID, C_FIRST_NAME, C_LAST_NAME, C_BIRTH_YEAR, C_BIRTH_COUNTRY, C_LAST_REVIEW_DATE) VALUES ('ZZZZZZZZZZZZZZZZ', 'Kimberly2', 'Hyatt2', 1979, 'SRI LANKA', '2452620');
UPDATE POC.SNOWFLAKE_POC.CUSTOMER_STAGE
SET C_BIRTH_COUNTRY = 'POLAND',
    C_BIRTH_YEAR = 1992
WHERE C_CUSTOMER_ID = 'AAAAAAAAGHFEHNBA';
INSERT INTO POC.SNOWFLAKE_POC.CUSTOMER_STAGE (C_CUSTOMER_ID, C_FIRST_NAME, C_LAST_NAME, C_BIRTH_YEAR, C_BIRTH_COUNTRY, C_LAST_REVIEW_DATE) VALUES ('RRRRRRRRRRRRRRRR', 'KAMIL', 'KARTON', 1969, 'SRI LANKA', '2452320');
DELETE FROM POC.SNOWFLAKE_POC.CUSTOMER_STAGE WHERE C_CUSTOMER_ID = 'AAAAAAAAAHFEHNBA';
UPDATE POC.SNOWFLAKE_POC.CUSTOMER_STAGE
SET C_BIRTH_COUNTRY = 'GERMANY',
    C_BIRTH_YEAR = 1997
WHERE C_CUSTOMER_ID = 'AAAAAAAACHFEHNBA';