CREATE OR REPLACE TABLE POC.SNOWFLAKE_POC.CUSTOMER_TARGET (
    C_CUSTOMER_ID          VARCHAR(16) NOT NULL,
    C_FIRST_NAME           VARCHAR(20),
    C_LAST_NAME            VARCHAR(30),
    C_BIRTH_YEAR           NUMBER,
    C_BIRTH_COUNTRY        VARCHAR(20),
    C_LAST_REVIEW_DATE     VARCHAR(10),
    FROM_TIMESTAMP         TIMESTAMP_NTZ(9),
    TO_TIMESTAMP           TIMESTAMP_NTZ(9)
)